DROP DATABASE IF EXISTS votd;
CREATE DATABASE IF NOT EXISTS votd;
USE votd;

CREATE TABLE config (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  guildID VARCHAR(18) NOT NULL,
  votdChannel VARCHAR(18) DEFAULT NULL,
  votdTimeHour VARCHAR(2) DEFAULT NULL,
  votdTimeMinute VARCHAR(2) DEFAULT NULL,
  votdTimeTimezone VARCHAR(100) DEFAULT NULL
);